### ISSUE TITLE
Should be option to see completed task list

### ISSUE THREAD

**Issue by mrasif** [mrinjamul/gtodo#2]
**Describe the bug**
Undone feature function is not handy, because it's need todo id to undone. But you user deleted a task then how he can see the task ID.

**To Reproduce**
1. Create a task
2. Delete that task
3. Now see the list, can't find deleted task ID

**Solution**
There should be an option to see deleted task then user can undone that task.

**Comment by mrinjamul** [comment]
Undone subcommand doesn't restore deleted task. It's for mark a done task as undone.

**Comment by mrasif** [comment]
Thanks for clarification, but still need a command to see the list of completed task (Done task). It is difficult for everyone to remember the number of completed task.

**Comment by mrinjamul** [comment]
You should read docs first. There is a command to see done tasks. 
```sh
gtodo list --done
```
